version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yazilim_testi_proje_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - djangonetwork

  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge
